# Backend
backend = "glx";

corner-radius = 10;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'i3bar'",
];

# Performance/Stability
vsync = true;
use-damage = true;

# Transparency
inactive-opacity = 0.95;
active-opacity = 1.0;
frame-opacity = 0.95;
opacity-rule = [
  "100:class_g = 'kitty'",
  "100:class_g = 'firefox'"
];


# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# Shadows 
shadow = false;

